### ISSUE TITLE
Can't run application

### ISSUE THREAD

**Issue by locskot** [peerwaya/flutter_call_kit#22]
There is a problem during the building step. 
My steps:
1. cd ios
2. flutter clean
3. flutter pub get
4. pod update  (log item is: Installing flutter_call_kit (0.0.1))

![Screenshot at Apr 28 14-18-31](https://user-images.githubusercontent.com/16982464/116395476-d7f33600-a82c-11eb-8eaf-54bffa10c18c.png)

Here is the flutter doctor -v output
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-arm, locale ru-RU)
    • Flutter version 1.22.6 at /users/locskot/dev/sdk/Flutter
    • Framework revision 9b2d32b605 (3 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/locskot/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

**Comment by jrkim123us** [comment]
I rebuilt yesterday and got the same error. I thought that the major version of flutter upgrade I was doing was the problem, but it doesn't seem to be.

[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale ko-KR)
    • Flutter version 2.0.5 at /Users/jongrokkim/Documents/tools/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jongrokkim/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/jongrokkim/Library/Android/sdk
    • Java binary at: /Users/jongrokkim/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

![스크린샷 2021-04-29 오전 11 22 19](https://user-images.githubusercontent.com/3949811/116495084-2c55ee80-a8dd-11eb-897f-b0f13361ce8a.png)

**Comment by jrkim123us** [comment]
Cause of problem: AVFoundation.framework doesn't seem to be included at build time (exact cause is unknown)
1. First found solution (settings disappear when using flutter clean)
flutter_call_kit> Build Phases> Link Binary With Libraries
![스크린샷 2021-04-29 오후 4 20 44](https://user-images.githubusercontent.com/3949811/116521693-43153900-a90f-11eb-9341-fd5974132ff4.png)

2. Source Modification
ios> flutter_call_kit.podspec
Add the following.

```
s.preserve_paths = 'AVFoundation.framework'
s.xcconfig = { 'OTHER_LDFLAGS' => '-framework AVFoundation' }
s.vendored_frameworks = 'AVFoundation.framework'
```

https://github.com/peerwaya/flutter_call_kit/pull/23 Hope this solves the problem well.

**Comment by locskot** [comment]
Thank you!
It works!

**Comment by 0radek** [comment]
+1, thanks for this fix. I hope your PR is merged soon.

**Comment by otgonbyrb** [comment]
Anyone can run on xcode 13 beta? Still getting same error after added AVFoundation.framework to Link Binary With Libraries and update flutter_call_kit.podspec.
