### ISSUE TITLE
Missing submodule 'AVFoundation.AVAudioSession'

### ISSUE THREAD

**Issue by zhukeev** [peerwaya/flutter_call_kit#24]
Can't run saying /Users/user/flutter2/.pub-cache/git/flutter_call_kit-f6310f0b3c574235a8dd7b605730d56a79bc3415/ios/Classes/FlutterCallKitPlugin.m:3:2: Missing submodule 'AVFoundation.AVAudioSession'

**Comment by yukitaka13-1110** [comment]
@zhukeev Did you find any solution?
