### ISSUE TITLE
End a call in the background

### ISSUE THREAD

**Issue by VictorUvarov** [peerwaya/flutter_call_kit#6]
Currently you can only report a new call in the background with
```swift
FlutterCallKitPlugin.reportNewIncomingCall(uuid, handle: handle, handleType: handleType, hasVideo: true, localizedCallerName: caller, fromPushKit: true)
```
is it possible to add a similar static method to also end the call.

Maybe something like this
```
FlutterCallKitPlugin.reportEndCall(uuid, ....)
```

Currently I have to extend your plugin to get it working
```swift
extension FlutterCallKitPlugin {
    static func reportEndCall(_ uuid: String) {
        if #available(iOS 10.0, *) {
            let endCallAction = CXEndCallAction.init(call: UUID(uuidString: uuid)!)
            let transaction = CXTransaction(action: endCallAction)
            
            CXCallController().request(transaction) { (error) in
                if error != nil {
                    endCallAction.fail()
                }
                endCallAction.fulfill()
            }
        }
    }
}
```

**Comment by yukitaka13-1110** [comment]
Hi! @VictorUvarov 
I have a question. Could you call event listener `performAnswerCallAction` ?
I could catch event only `_didActivateAudioSession`.

**Comment by VictorUvarov** [comment]
I don't know. I haven't tried since all the callbacks work on the dart side.

**Comment by yukitaka13-1110** [comment]
@VictorUvarov 
I see. Please tell me if you try.
Thank you!

**Comment by aososam** [comment]
@VictorUvarov I am also looking for a method to end the call programmatically, since I get an error, when rejecting the call:

No implementation found for method endCall on channel com.peerwaya/flutter_callkit_plugin)

How can I use your code to extend the plugin? or did you find another solution for this? Thank you.

**Comment by VictorUvarov** [comment]
I use this now. https://pub.dev/packages/flutter_callkit_voximplant
